### ISSUE TITLE
A code to print housie tickets in c

### ISSUE THREAD

**Issue by yashviiii** [Pavan-Kamthane/C_langauege_#106]
A simple code that will generate unique housie tickets every time.

**Comment by Bitan-Kundu** [comment]
Hello Sir, Can you assign this issue to me?

**Comment by Bitan-Kundu** [comment]
> A simple code that will generate unique housie tickets every time.

Hello Sir, Can you assign this issue to me?

**Comment by VedantKCSE** [comment]
> > A simple code that will generate unique housie tickets every time.
> 
> Hello Sir, Can you assign this issue to me?

Assigned the issue @Bitan-Kundu

**Comment by yashviiii** [comment]
Hello i raised this issue, pls assign it to me

**Comment by yashviiii** [comment]
@VedantKCSE

**Comment by Bitan-Kundu** [comment]
Hello sir, Can you assign this issue to me? Now I am free.

**Comment by Pavan-Kamthane** [comment]
@Bitan-Kundu can PR directly
