### ISSUE TITLE
Upload a simple C language program in your named folder

### ISSUE THREAD

**Issue by Pavan-Kamthane** [Pavan-Kamthane/C_langauege_#152]
Create a folder of your name 
then add you code

### **"How to contribute in repo and what is  PR ?"**
This is the main **AGENDA** Of this repository.

**You can create a PR directly, no need to assign anyone**

**Comment by pantbibek21** [comment]
Okay, sure sir.

**Comment by Soumyata12** [comment]
I want to contribute in this.

**Comment by manishpoko** [comment]
Would love to contribute to this!
