### ISSUE TITLE
First star this repo and then add a simple basic c program

### ISSUE THREAD

**Issue by Pavan-Kamthane** [Pavan-Kamthane/C_langauege_#21]
Create a folder of your name 
then add you code

### **"How to contribute in repo and what is  PR ?"**
This is the main **AGENDA** Of this repository.

**Comment by aditya-agr** [comment]
I want to contribute .

**Comment by Pavan-Kamthane** [comment]
@aditya-agr Ok then contribute

**Comment by aditya-agr** [comment]
please assign issue to me with labels .

**Comment by Pavan-Kamthane** [comment]
@aditya-agr can PR directly I will add label to your PR don't worry.

**Comment by pabitra0011** [comment]
Hello @Pavan-Kamthane I want to add some string related coding (like check palindrome, reverse a string etc. ), please give me this opportunity to contribute some simple coding, actually this could be my first open-source contribution ever. 
                                                                                                                                                                                          Thank you...

**Comment by Pavan-Kamthane** [comment]
@pabitra0011 all types of code accepted

**Comment by Devansh042005** [comment]
hello sir can you assign this issue to me

**Comment by ShaluMishra13** [comment]
please assign this to me

**Comment by ShaluMishra13** [comment]
I can do it very well please assign this to me

**Comment by Pavan-Kamthane** [comment]
@KadhamVj23 Ok Ur Assigned
