### ISSUE TITLE
Add Any simple C lang Program 

### ISSUE THREAD

**Issue by Pavan-Kamthane** [Pavan-Kamthane/C_langauege_#4]
### **"How to contribute in repo and what is  PR ?"**
This is the main **AGENDA** Of this repository.

Add any simple c language program.

**Comment by Pavan-Kamthane** [comment]
#3 Thanks For contributing

**Comment by mb-008** [comment]
please assign me this

**Comment by Pavan-Kamthane** [comment]
@mb-008 No need to assgin PR directly
