### ISSUE TITLE
Add A C program In This Repo And Create your name folder In which You have to add this program

### ISSUE THREAD

**Issue by Pavan-Kamthane** [Pavan-Kamthane/C_langauege_#9]
### **"How to contribute in repo and what is  PR ?"**
This is the main **AGENDA** Of this repository.

Add any simple c language program.

### Remember First Create A folder of your name

**Comment by Krish-Paul** [comment]
Please assign this to me. This is my 1st attempt at Hacktoberfest.

**Comment by Pavan-Kamthane** [comment]
You can PR directly

**Comment by Pavan-Kamthane** [comment]
Check my contributor.md file
